name: "Push workflow"
description: "Push workflow in remote or local repository"
author: "Vinayak Jadhav"

inputs:
  gh-token:
    description: "Github Token or Pat Token"
    required: true
  run-id:
    description: "Run id of workflow"
    required: true
  payload:
    description: "Json payload"
    required: true
  remote-repo:
    description: "Remote repository"
    required: false
  remote-branch:
    description: "Remote repository branch"
    required: false

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "check-square"
  color: "white"