name: "Push workflow"
description: "Push workflow in remote or local repository"
author: "Vinayak Jadhav"

inputs:
  gh-token:
    description: "Github Token"
    required: true
  run-id:
    description: "Run id of workflow"
    required: true
  payload:
    description: "Json payload"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "check-square"
  color: "white"