name: Build

on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: ./
      with:
        gh-token: ${{ github.token }}
        run-id: "114803271"
        payload: "{}"