name: Build

on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Run workflow'
      uses: vinayaja/push-workflow@feature/remote-push
      with:
        gh-token: ${{ secrets.PAT_TOKEN }}
        run-id: "114772299"
        payload: '{}'
        remote-branch: 'main'
        remote-repo: 'vinayaja/replace-tokens'